
import React, { useState, useEffect } from 'react';
import { AppView, Recipe, AppSettings, DEFAULT_APP_SETTINGS } from './types';
import RecipeCard from './components/RecipeCard';
import CookingMode from './components/CookingMode';
import RecipeSetup from './components/RecipeSetup';
import IngredientScanner from './components/IngredientScanner';
import CreateFromYouTube from './components/CreateFromYouTube';
import Login from './components/Login';
import Profile from './components/Profile';
import Settings from './components/Settings';
import { getAllRecipes, getAppSettings } from './services/dbService';
import { subscribeToAuthState, signOut } from './services/authService';
import type { User } from 'firebase/auth';

const BOTTOM_NAV_VIEWS: AppView[] = [
  AppView.Home,
  AppView.Inventory,
  AppView.Profile,
  AppView.RecipeDetail,
  AppView.RecipeSetup,
  AppView.CreateFromYouTube,
];

const App: React.FC = () => {
  const [authUser, setAuthUser] = useState<User | null>(null);
  const [authChecked, setAuthChecked] = useState(false);
  const [currentView, setCurrentView] = useState<AppView>(AppView.Home);
  const [recipes, setRecipes] = useState<Recipe[]>([]);
  const [selectedRecipe, setSelectedRecipe] = useState<Recipe | null>(null);
  const [scaledRecipe, setScaledRecipe] = useState<Recipe | null>(null);
  const [appSettings, setAppSettings] = useState<AppSettings>(DEFAULT_APP_SETTINGS);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    const unsubscribe = subscribeToAuthState((user) => {
      setAuthUser(user);
      setAuthChecked(true);
    });
    return () => unsubscribe();
  }, []);

  useEffect(() => {
    if (!authUser) {
      setIsLoading(false);
      return;
    }
    setIsLoading(true);
    const loadData = async () => {
      try {
        const uid = authUser.uid;
        const [dbRecipes, dbSettings] = await Promise.all([
          getAllRecipes(uid),
          getAppSettings(uid),
        ]);
        setRecipes(dbRecipes);
        setAppSettings(dbSettings);
      } catch (err) {
        console.error("Failed to load data", err);
      } finally {
        setIsLoading(false);
      }
    };
    loadData();
  }, [authUser]);

  const handleRecipeClick = (recipe: Recipe) => {
    setSelectedRecipe(recipe);
    setCurrentView(AppView.RecipeDetail);
  };

  const goToSetup = () => {
    setCurrentView(AppView.RecipeSetup);
  };

  const onSetupComplete = (newRecipe: Recipe) => {
    setScaledRecipe(newRecipe);
    setRecipes(prev => prev.map(r => r.id === newRecipe.id ? newRecipe : r));
    setCurrentView(AppView.CookingMode);
  };

  const handleScannedRecipe = (rec: any) => {
    // For the prototype, we create a temporary recipe object
    // In a real app, this would be fetched from a database or fully generated by AI
    const newRecipe: Recipe = {
      id: rec.id || Math.random().toString(),
      title: rec.title,
      description: rec.description,
      image: `https://picsum.photos/seed/${rec.title}/800/600`,
      difficulty: 'Medium',
      cookTime: '20 min',
      prepTime: '10 min',
      servings: 2,
      ingredients: ['Scanned ingredients used...'],
      steps: ['Step 1: Prep your ingredients', 'Step 2: Cook according to recipe details', 'Step 3: Enjoy!']
    };
    setSelectedRecipe(newRecipe);
    setCurrentView(AppView.RecipeDetail);
  };

  const renderLoading = (message: string) => (
    <div className="max-w-md mx-auto h-screen flex items-center justify-center bg-[#fcfcf9]">
      <div className="flex flex-col items-center gap-4">
        <div className="w-12 h-12 border-4 border-emerald-500 border-t-transparent rounded-full animate-spin" />
        <p className="text-stone-400 font-bold text-xs uppercase tracking-widest">{message}</p>
      </div>
    </div>
  );

  if (!authChecked) return renderLoading('Loading...');
  if (!authUser) return <Login onSuccess={() => {}} />;
  if (isLoading) return renderLoading('Initializing...');

  const renderHome = () => (
    <div className="space-y-8 pb-24">
      <header className="px-6 pt-8 space-y-2">
        <h1 className="text-3xl font-bold text-stone-800 tracking-tight">Hello, Chef!</h1>
        <p className="text-stone-500">What are we cooking today?</p>
      </header>

      <div className="px-6">
        <div className="relative">
          <span className="absolute inset-y-0 left-4 flex items-center text-stone-400">
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" /></svg>
          </span>
          <input
            type="text"
            placeholder="Search recipes or ingredients..."
            className="w-full bg-stone-100 rounded-2xl py-3 pl-12 pr-4 focus:outline-none focus:ring-2 focus:ring-emerald-500 transition-all text-sm"
          />
        </div>
      </div>

      <section className="px-6 space-y-4">
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-bold text-stone-800">Local SQLite Collection</h2>
          <button className="text-emerald-500 text-sm font-semibold">Sync</button>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {recipes.map(recipe => (
            <RecipeCard key={recipe.id} recipe={recipe} onClick={handleRecipeClick} />
          ))}
        </div>
      </section>

      <section className="px-6 space-y-4">
        <div
          onClick={() => setCurrentView(AppView.CreateFromYouTube)}
          className="bg-stone-800 rounded-[2.5rem] p-8 text-white flex items-center justify-between shadow-xl cursor-pointer hover:bg-stone-700 active:scale-[0.98] transition-all overflow-hidden relative group"
        >
          <div className="absolute top-0 right-0 w-32 h-32 bg-red-500/10 rounded-full -mr-16 -mt-16 group-hover:scale-150 transition-transform duration-700"></div>
          <div className="space-y-1 relative z-10">
            <h3 className="font-bold text-xl">Create from YouTube</h3>
            <p className="text-stone-300 text-sm opacity-80 leading-tight">Turn a cooking video into a recipe<br />with step timestamps</p>
          </div>
          <div className="bg-white text-red-600 p-4 rounded-2xl shadow-lg relative z-10">
            <svg className="w-7 h-7" fill="currentColor" viewBox="0 0 24 24"><path d="M23.498 6.186a3.016 3.016 0 0 0-2.122-2.136C19.505 3.545 12 3.545 12 3.545s-7.505 0-9.377.505A3.017 3.017 0 0 0 .502 6.186C0 8.07 0 12 0 12s0 3.93.502 5.814a3.016 3.016 0 0 0 2.122 2.136c1.871.505 9.376.505 9.376.505s7.505 0 9.377-.505a3.015 3.015 0 0 0 2.122-2.136C24 15.93 24 12 24 12s0-3.93-.502-5.814zM9.545 15.568V8.432L15.818 12l-6.273 3.568z"/></svg>
          </div>
        </div>
        <div
          onClick={() => setCurrentView(AppView.Scanner)}
          className="bg-emerald-900 rounded-[2.5rem] p-8 text-white flex items-center justify-between shadow-xl cursor-pointer hover:bg-emerald-800 active:scale-[0.98] transition-all overflow-hidden relative group"
        >
          <div className="absolute top-0 right-0 w-32 h-32 bg-emerald-500/10 rounded-full -mr-16 -mt-16 group-hover:scale-150 transition-transform duration-700"></div>
          <div className="space-y-1 relative z-10">
            <h3 className="font-bold text-xl">Scan Ingredients</h3>
            <p className="text-emerald-200 text-sm opacity-80 leading-tight">AI will suggest what to cook<br />based on your pantry</p>
          </div>
          <div className="bg-white text-emerald-900 p-4 rounded-2xl shadow-lg relative z-10">
            <svg className="w-7 h-7" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M3 9a2 2 0 012-2h.93a2 2 0 001.664-.89l.812-1.22A2 2 0 0110.07 4h3.86a2 2 0 011.664.89l.812 1.22A2 2 0 0018.07 7H19a2 2 0 012 2v9a2 2 0 01-2 2H5a2 2 0 01-2-2V9z" /><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 13a3 3 0 11-6 0 3 3 0 016 0z" /></svg>
          </div>
        </div>
      </section>
    </div>
  );

  const renderRecipeDetail = () => {
    if (!selectedRecipe) return null;
    return (
      <div className="bg-white min-h-screen pb-32 animate-in fade-in duration-300">
        <div className="relative h-[40vh]">
          <img
            src={selectedRecipe.image}
            alt={selectedRecipe.title}
            className="w-full h-full object-cover"
          />
          <button
            onClick={() => setCurrentView(AppView.Home)}
            className="absolute top-8 left-6 p-2 bg-white/90 backdrop-blur-sm rounded-xl text-stone-800 shadow-md z-10"
          >
            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 19l-7-7 7-7" /></svg>
          </button>
        </div>

        <div className="px-6 pt-8 space-y-6">
          <div className="space-y-2">
            <h1 className="text-3xl font-bold text-stone-800 tracking-tight">{selectedRecipe.title}</h1>
            <p className="text-stone-500 leading-relaxed">{selectedRecipe.description}</p>
          </div>

          <div className="flex justify-between items-center py-4 border-y border-stone-100">
            <div className="text-center">
              <p className="text-xs text-stone-400 font-bold uppercase mb-1">Time</p>
              <p className="font-bold text-stone-800">{selectedRecipe.cookTime}</p>
            </div>
            <div className="text-center">
              <p className="text-xs text-stone-400 font-bold uppercase mb-1">Level</p>
              <p className="font-bold text-stone-800">{selectedRecipe.difficulty}</p>
            </div>
            <div className="text-center">
              <p className="text-xs text-stone-400 font-bold uppercase mb-1">Serves</p>
              <p className="font-bold text-stone-800">{selectedRecipe.servings}</p>
            </div>
          </div>

          <div className="space-y-4">
            <h2 className="text-xl font-bold text-stone-800">Ingredients</h2>
            <ul className="space-y-3">
              {selectedRecipe.ingredients.map((ing, i) => (
                <li key={i} className="flex items-center gap-3 text-stone-600">
                  <div className="w-1.5 h-1.5 rounded-full bg-emerald-500"></div>
                  {ing}
                </li>
              ))}
            </ul>
          </div>

          {selectedRecipe.videoUrl && (
            <a
              href={selectedRecipe.videoUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-2 py-3 px-4 bg-stone-100 rounded-2xl text-stone-700 font-medium text-sm hover:bg-stone-200"
            >
              <svg className="w-5 h-5 text-red-600" fill="currentColor" viewBox="0 0 24 24"><path d="M23.498 6.186a3.016 3.016 0 0 0-2.122-2.136C19.505 3.545 12 3.545 12 3.545s-7.505 0-9.377.505A3.017 3.017 0 0 0 .502 6.186C0 8.07 0 12 0 12s0 3.93.502 5.814a3.016 3.016 0 0 0 2.122 2.136c1.871.505 9.376.505 9.376.505s7.505 0 9.377-.505a3.015 3.015 0 0 0 2.122-2.136C24 15.93 24 12 24 12s0-3.93-.502-5.814zM9.545 15.568V8.432L15.818 12l-6.273 3.568z"/></svg>
              Watch recipe video
            </a>
          )}

          <div className="space-y-4">
            <h2 className="text-xl font-bold text-stone-800">Instructions</h2>
            <div className="space-y-6">
              {selectedRecipe.steps.map((step, i) => (
                <div key={i} className="flex gap-4">
                  <span className="flex-shrink-0 w-8 h-8 rounded-full bg-stone-100 flex items-center justify-center text-sm font-bold text-stone-500">
                    {i + 1}
                  </span>
                  <p className="text-stone-600 leading-relaxed pt-1">{step}</p>
                </div>
              ))}
            </div>
          </div>
        </div>

        <div className="fixed bottom-0 left-0 right-0 p-6 bg-gradient-to-t from-white via-white to-white/0 z-50">
          <button
            onClick={goToSetup}
            className="w-full bg-emerald-600 text-white font-black py-4 rounded-2xl shadow-lg hover:bg-emerald-700 active:scale-[0.98] transition-all flex items-center justify-center gap-2"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M14.752 11.168l-3.197-2.132A1 1 0 0010 9.87v4.263a1 1 0 001.555.832l3.197-2.132a1 1 0 000-1.664z" /><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
            PREPARE RECIPE
          </button>
        </div>
      </div>
    );
  };

  return (
    <div className="max-w-md mx-auto min-h-screen bg-[#fcfcf9] shadow-2xl relative">
      {currentView === AppView.Home && renderHome()}
      {currentView === AppView.RecipeDetail && renderRecipeDetail()}
      {currentView === AppView.RecipeSetup && selectedRecipe && authUser && (
        <RecipeSetup
          recipe={selectedRecipe}
          onComplete={onSetupComplete}
          onCancel={() => setCurrentView(AppView.RecipeDetail)}
          appSettings={appSettings}
          userId={authUser.uid}
        />
      )}
      {currentView === AppView.CookingMode && scaledRecipe && (
        <CookingMode
          recipe={scaledRecipe}
          onExit={() => setCurrentView(AppView.RecipeDetail)}
          appSettings={appSettings}
        />
      )}
      {currentView === AppView.Scanner && (
        <IngredientScanner
          onClose={() => setCurrentView(AppView.Home)}
          onSelectRecipe={handleScannedRecipe}
        />
      )}
      {currentView === AppView.Profile && authUser && (
        <Profile
          user={authUser}
          onBack={() => setCurrentView(AppView.Home)}
          onOpenSettings={() => setCurrentView(AppView.Settings)}
        />
      )}
      {currentView === AppView.Settings && authUser && (
        <Settings
          userId={authUser.uid}
          onBack={() => setCurrentView(AppView.Profile)}
          onSaved={(s) => setAppSettings(s)}
        />
      )}
      {currentView === AppView.CreateFromYouTube && authUser && (
        <CreateFromYouTube
          userId={authUser.uid}
          onCreated={(recipe) => {
            setRecipes((prev) => [...prev.filter((r) => r.id !== recipe.id), recipe]);
            setSelectedRecipe(recipe);
            setCurrentView(AppView.RecipeDetail);
          }}
          onCancel={() => setCurrentView(AppView.Home)}
        />
      )}

      {BOTTOM_NAV_VIEWS.includes(currentView) && (
        <nav className="fixed bottom-0 left-0 right-0 max-w-md mx-auto bg-white/80 backdrop-blur-md border-t border-stone-200 px-8 py-4 flex items-center justify-between z-40">
          <button
            onClick={() => setCurrentView(AppView.Home)}
            className={`p-2 rounded-xl transition-colors ${currentView === AppView.Home ? 'text-emerald-600 bg-emerald-50' : 'text-stone-400'}`}
          >
            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M3 12l2-2m0 0l7-7 7-7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" /></svg>
          </button>
          <button className="p-2 text-stone-400">
            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4" /></svg>
          </button>
          <button
            onClick={() => setCurrentView(AppView.Profile)}
            className={`p-2 rounded-xl transition-colors ${currentView === AppView.Profile ? 'text-emerald-600 bg-emerald-50' : 'text-stone-400'}`}
            title="Profile"
          >
            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" /></svg>
          </button>
          <button
            onClick={() => signOut()}
            className="p-2 text-stone-400 hover:text-stone-600"
            title="Sign out"
          >
            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" /></svg>
          </button>
        </nav>
      )}
    </div>
  );
};

export default App;
